# Generated by Django 3.0.3 on 2020-05-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpb', '0002_auto_20200529_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
